// <auto-generated />
namespace SCM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTblSupplier_Rakib : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTblSupplier_Rakib));
        
        string IMigrationMetadata.Id
        {
            get { return "201910291226238_addTblSupplier_Rakib"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
